title: "Nguyen Thi Quynh Chi"
description: "Sinh vien Khoa Quan tri Kinh doanh - Truong Dai hoc Ngoai thuong"
author: "Nguyen Thi Quynh Chi"

# VI EM DANG DUNG PROJECT REPO: github-portfolio
url: "https://nguyenthiquynhchivnex.github.io"
baseurl: "/github-portfolio"

collections:
  pages:
    output: true
    permalink: /:name/

timezone: Asia/Ho_Chi_Minh
markdown: kramdown
